### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by kweeky** [dunjeon/mod-TimeIsTime#1]
`/azerothcore/modules/mod-TimeIsTime/src/TimeIsTime.cpp:48:40: fatal error: no member named 'GetGameTime' in 'IWorld'
        uint32 speed_time  = ((sWorld->GetGameTime() - sWorld->GetUptime()) + (sWorld->GetUptime() * stimeistime_speed_rate)); `

When compiling with latest AzerothCore at time of writing.

**Comment by dunjeon** [comment]
Fixed Thanks @kweeky  for the report
